USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'AALVES')
	DROP DATABASE AALVES
GO

CREATE DATABASE AALVES
GO
USE AALVES
GO
CREATE TABLE CURSO (
	ID_CURSO INT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
)
GO
CREATE TABLE PERIODO (
	ID_PERIODO INT PRIMARY KEY
)
GO
CREATE TABLE ALUNO (
	ID_ALUNO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(80) NOT NULL,
	EMAIL VARCHAR(80) NOT NULL,
	SEXO VARCHAR(20) NOT NULL,
	SENHA VARCHAR(80) NOT NULL,
	RUA VARCHAR(80) NOT NULL,
	NUMERO INT NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	ID_CURSO INT FOREIGN KEY REFERENCES CURSO(ID_CURSO),
	ID_PERIODO INT FOREIGN KEY REFERENCES PERIODO(ID_PERIODO)
)
GO
--CREATE TABLE PROFESSOR (
--	ID_PROFESSOR INT PRIMARY KEY IDENTITY(1,1),
--	NOME VARCHAR(80) NOT NULL,
--	SEXO VARCHAR(20) NOT NULL,
--  RG VARCHAR(50) NOT NULL,
--  CPF VARCHAR (50) NOT NUL,
--  RUA VARCHAR (80) NOT NULL,
--	NUMERO INT NOT NULL,
--	BAIRRO VARCHAR(20) NOT NULL,
--	CEP VARCHAR(9) NOT NULL,
--	CIDADE VARCHAR(50) NOT NULL,
--	ESTADO VARCHAR(30) NOT NULL,
--	TELEFONE VARCHAR(20) NOT NULL,
--  CELULAR VARCHAR (20) NOT NULL,
--	EMAIL VARCHAR(80) NOT NULL,
--  SENHA VARCHAR (80) NOT NULL
--)
--GO
--CREATE TABLE FUNCIONARIO (
--	ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
--	NOME VARCHAR(80) NOT NULL,
--	SEXO VARCHAR(20) NOT NULL,
--  RG VARCHAR(50) NOT NULL,
--  CPF VARCHAR (50) NOT NUL,
--  RUA VARCHAR (80) NOT NULL,
--	NUMERO INT NOT NULL,
--	BAIRRO VARCHAR(20) NOT NULL,
--	CEP VARCHAR(9) NOT NULL,
--	CIDADE VARCHAR(50) NOT NULL,
--	ESTADO VARCHAR(30) NOT NULL,
--	TELEFONE VARCHAR(20) NOT NULL,
--  CELULAR VARCHAR (20) NOT NULL,
--	EMAIL VARCHAR(80) NOT NULL,
--  SENHA VARCHAR (80) NOT NULL
--	CARGO VARCHAR(30)
--)
--GO
--CREATE TABLE NOTAS (
--	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO)
--)
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Jessica Fuller', 'jfuller0@eventbrite.com', 'F', 'Mandrake', '50993', 8, 'Jacksonville', 'Florida', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Annie Wheeler', 'awheeler1@google.ca', 'F', 'Pawling', '80412', 8, 'Las Vegas', 'Nevada', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Brandon Murphy', 'bmurphy2@washingtonpost.com', 'M', 'Transport', '5', 8, 'Portland', 'Oregon', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Douglas Edwards', 'dedwards3@oaic.gov.au', 'M', 'Golf View', '6039', 8, 'Oklahoma City', 'Oklahoma', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Alan Duncan', 'aduncan4@aol.com', 'M', 'Springs', '67', 8, 'Arlington', 'Virginia', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Juan Reed', 'jreed5@cbslocal.com', 'M', 'Rockefeller', '4517', 8, 'Amarillo', 'Texas', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Judy Gilbert', 'jgilbert6@booking.com', 'F', 'Northview', '3346', 8, 'Rochester', 'New York', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Scott Bishop', 'sbishop7@msn.com', 'M', 'Derek', '01', 8, 'Cincinnati', 'Ohio', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('Bobby Tucker', 'btucker8@amazon.de', 'M', 'Corben', '30', 8, 'Roanoke', 'Virginia', 11);
--insert into ALUNO (NOME, EMAIL, SEXO, RUA, NUMERO, CEP, CIDADE, ESTADO, TELEFONE) values ('John Wagner', 'jwagner9@intel.com', 'M', 'Truax', '72424', 8, 'Bethesda', 'Maryland', 11);
--GO
INSERT INTO CURSO VALUES (1, 'BASICO')
INSERT INTO CURSO VALUES (2, 'COMPLETO')
INSERT INTO CURSO VALUES (3, 'EXPRESSO')

INSERT INTO PERIODO VALUES (1)
INSERT INTO PERIODO VALUES (2)
INSERT INTO PERIODO VALUES (3)
SELECT * FROM ALUNO
SELECT * FROM CURSO
SELECT * FROM PERIODO
--SELECT NOME, EMAIL, TELEFONE FROM ALUNO 
--delete from ALUNO where ID_ALUNO = 2


--INSERT INTO ALUNO VALUES ('ERT','ERG','MASC','SWF','ergdrfg', 5, 111111, 'EEF', 'WEF', '213345', 1, 3)